# Generated by Django 5.0.6 on 2024-07-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=250)),
                ('categoria', models.CharField(max_length=30)),
                ('img_portada', models.CharField(max_length=255)),
            ],
        ),
    ]
