# Generated by Django 5.0.3 on 2024-07-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='url_music_download',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
